---
title: "AI Today Compared to Dartmouth Workshop"
desciption: "Essay for Lab-1 on Today's AI"
author: Abdul Khader, Syed
format:
    html:
        code-fold: false
    pdf: 
        date: 10 October 2022
execute: 
  enabled: true
---

**How has the focus on AI shifted from this original proposal to today? Specifically, talk about imbuing AI with human thinking and intelligence.**

The major change in today's AI would be the proper definition of tasks and problems being solved, whereas, in the Dartmouth workshop proposal, the problems which were trying to be solved were abstract and high-level. 

Today's AI is more and more data dependent where with lots of data available today, the models are based on learning patterns in the data rather than learning the general environment. This approach of learning from data which is curated and marked, known as supervised learning, has limitations in scaling.

We humans from childhood start learning patterns from what we see even without many labels, and we use the prior information we learn through life to learn new things. The field of AI has been trying to simulate this phenomenon of learning from the environment directly without having labelled data, by exposing the AI to a large magnitude of unlabelled data, which allows the system to learn the representation of the world and objects and form an approximate model of common-sense. This method today was coined as the dark matter of intelligence[1]. 

Another common method today to build AI is how humans build intelligence by playing games and practising. AI today is trained to play games by playing against itself a very large number of times and to self-improve with time, which was also part of the proposal in the workshop.


**Your commentary on the long-term implications of the workshop.**

The workshop was the spark to start a huge field, which went through multiple ups and downs. The idea of computers being able to simulate or solve any real-world problem is still not achieved, but the progress so far has been great with various successes in the field of vision and language. The workshop brainstormed about different problems computers can solve on their own, and made people think about computers as not just tools to perform instructions but as intelligent beings.

**References**

[1] LeCun, Yan & Misra, Ishan. Self-supervised learning: The dark matter of intelligence. Meta AI. https://ai.facebook.com/blog/self-supervised-learning-the-dark-matter-of-intelligence/