<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abdul Khader, Syed">
<meta name="description" content="Review of Linear Algebra and Calculus">

<title>Plaksha - Machine Learning Homework I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Plaksha</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Machine Learning Homework I</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_Mathematics_I/index.html" class="sidebar-item-text sidebar-link">Mathematics I</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_Python_Programming/index.html" class="sidebar-item-text sidebar-link">Intro to Programming</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_Intro_AI/index.html" class="sidebar-item-text sidebar-link">Intro to A.I.</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../04_DataVisualization/index.html" class="sidebar-item-text sidebar-link">Data Visualization</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../05_Mathematics_II/index.html" class="sidebar-item-text sidebar-link">Mathematics II</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../06_Intro_DSA/index.html" class="sidebar-item-text sidebar-link">Intro to DSA</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../07_MachineLearning_I/index.html" class="sidebar-item-text sidebar-link">Machine Learning I</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../09_Projects_DS/index.html" class="sidebar-item-text sidebar-link">Project of Data Science and Applications</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#problem-1" id="toc-problem-1" class="nav-link active" data-scroll-target="#problem-1">Problem 1</a>
  <ul class="collapse">
  <li><a href="#solution" id="toc-solution" class="nav-link" data-scroll-target="#solution">Solution</a></li>
  </ul></li>
  <li><a href="#problem-2" id="toc-problem-2" class="nav-link" data-scroll-target="#problem-2">Problem 2</a>
  <ul class="collapse">
  <li><a href="#solution-1" id="toc-solution-1" class="nav-link" data-scroll-target="#solution-1">Solution</a></li>
  </ul></li>
  <li><a href="#problem-3" id="toc-problem-3" class="nav-link" data-scroll-target="#problem-3">Problem 3</a></li>
  <li><a href="#problem-4" id="toc-problem-4" class="nav-link" data-scroll-target="#problem-4">Problem 4</a>
  <ul class="collapse">
  <li><a href="#solution-2" id="toc-solution-2" class="nav-link" data-scroll-target="#solution-2">Solution</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">(b)</a></li>
  </ul></li>
  <li><a href="#problem-5" id="toc-problem-5" class="nav-link" data-scroll-target="#problem-5">Problem 5</a>
  <ul class="collapse">
  <li><a href="#solution-3" id="toc-solution-3" class="nav-link" data-scroll-target="#solution-3">Solution</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Machine Learning Homework I</h1>
</div>

<div>
  <div class="description">
    Review of Linear Algebra and Calculus
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Abdul Khader, Syed </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>This symmetric matrix is called the Hadamard matrix and it has orthogonal columns:</p>
<p><span class="math display">\[
H =
\begin{bmatrix}
1 &amp; 1 &amp; 1 &amp; 1\\
1 &amp; -1 &amp; 1 &amp; -1\\
1 &amp; 1 &amp; -1 &amp; -1\\
1 &amp; -1 &amp; -1 &amp; 1
\end{bmatrix}
\]</span></p>
<p>also, <span class="math inline">\(H^2 = 4I\)</span></p>
<ol type="a">
<li>What is the determinant of <span class="math inline">\(H\)</span>?<br>
</li>
<li>What are the eigenvalues of <span class="math inline">\(H\)</span>?<br>
</li>
<li>What are the singular values of <span class="math inline">\(H\)</span>?</li>
</ol>
<section id="solution" class="level3">
<h3 class="anchored" data-anchor-id="solution">Solution</h3>
<section id="a" class="level4">
<h4 class="anchored" data-anchor-id="a">(a)</h4>
<p>We know <span class="math inline">\(det(A^2) = det(A)^2\)</span>, Given <span class="math inline">\(H^2 = 4I\)</span>,</p>
<p><span class="math inline">\(det(H) = \sqrt{det(H^2)} = \sqrt{det(4I)}\)</span></p>
<p>We also know that <span class="math inline">\(det(kA) = k^n det(A)\)</span>, where <span class="math inline">\(n\)</span> is the dimension of the square matrix <span class="math inline">\(A\)</span></p>
<p><span class="math inline">\(det(4I_4) = 4^4 det(I_4)\)</span> <span class="math display">\[
det(I_4) =
\begin{vmatrix}
1 &amp; 0 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 1 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1
\end{vmatrix} = 1*det(I_3) + 0 + 0 + 0
\]</span> <span class="math display">\[
det(I_3) =
\begin{vmatrix}
1 &amp; 0 &amp; 0 \\
0 &amp; 1 &amp; 0 \\
0 &amp; 0 &amp; 1 \\
\end{vmatrix} = 1*(1-0) + 0 + 0 = 1
\]</span> <span class="math display">\[\therefore det(I_4) = 1 * 1 = 1\]</span></p>
<p><span class="math display">\[det(4I_4) = 4^4 * 1 = 64\]</span></p>
<p><span class="math display">\[det(H) = \sqrt{det(H^2)} = \sqrt{det(4I)} = \sqrt{64} = 16\]</span></p>
</section>
<section id="b" class="level4">
<h4 class="anchored" data-anchor-id="b">(b)</h4>
<p>For Eigen Values of H, we need to solve the Characteristic equation which is <span class="math inline">\(|H - \lambda I| = 0\)</span></p>
<p><span class="math display">\[
det(H - \lambda I) =
\begin{vmatrix}
\begin{bmatrix}
1 &amp; 1 &amp; 1 &amp; 1\\
1 &amp; -1 &amp; 1 &amp; -1\\
1 &amp; 1 &amp; -1 &amp; -1\\
1 &amp; -1 &amp; -1 &amp; 1
\end{bmatrix}
-
\begin{bmatrix}
\lambda &amp; 0 &amp; 0 &amp; 0\\
0 &amp; \lambda &amp; 0 &amp; 0\\
0 &amp; 0 &amp; \lambda &amp; 0\\
0 &amp; 0 &amp; 0 &amp; \lambda
\end{bmatrix}
\end{vmatrix} =
\begin{vmatrix}
1-\lambda &amp; 1 &amp; 1 &amp; 1\\
1 &amp; -1-\lambda &amp; 1 &amp; -1\\
1 &amp; 1 &amp; -1-\lambda &amp; -1\\
1 &amp; -1 &amp; -1 &amp; 1-\lambda
\end{vmatrix}
\]</span></p>
<p>We know that the determinant doesn’t changes when we do row operations of subtracting a multiple of a row with another row.</p>
<p><span class="math inline">\(R_3 = R_3 - R_2\)</span></p>
<p><span class="math inline">\(R_4 = R_4 - R_2\)</span></p>
<p><span class="math inline">\(\begin{vmatrix} 1-\lambda &amp; 1 &amp; 1 &amp; 1\\ 1 &amp; -1-\lambda &amp; 1 &amp; -1\\ 0 &amp; 2+\lambda &amp; -2-\lambda &amp; 0\\ 0 &amp; \lambda &amp; -2 &amp; 2-\lambda \end{vmatrix} = 0\)</span></p>
<p><span class="math inline">\(= (1-\lambda) \begin{vmatrix} -1-\lambda &amp; 1 &amp; -1\\ 2+\lambda &amp; -2-\lambda &amp; 0\\ \lambda &amp; -2 &amp; 2-\lambda \end{vmatrix} - 1 \begin{vmatrix} 1 &amp; 1 &amp; -1\\ 0 &amp; -2-\lambda &amp; 0\\ 0 &amp; -2 &amp; 2-\lambda \end{vmatrix} + 1 \begin{vmatrix} 1 &amp; -1-\lambda &amp; -1\\ 0 &amp; 2+\lambda &amp; 0\\ 0 &amp; \lambda &amp; 2-\lambda \end{vmatrix} - 1 \begin{vmatrix} 1 &amp; -1-\lambda &amp; 1 \\ 0 &amp; 2+\lambda &amp; -2-\lambda\\ 0 &amp; \lambda &amp; -2 \end{vmatrix} = 0\)</span></p>
<p>For <span class="math inline">\(1^{st}\)</span> sub determinant</p>
<p><span class="math inline">\(\begin{vmatrix} -1-\lambda &amp; 1 &amp; -1\\ 2+\lambda &amp; -2-\lambda &amp; 0\\ \lambda &amp; -2 &amp; 2-\lambda \end{vmatrix} = -({1+\lambda})*(\lambda^2 - 4) - 1*(4 - \lambda^2) + (-1) * (\lambda^2 - 4)\)</span></p>
<p><span class="math inline">\(= (\lambda^2 - 4) * (-1 - \lambda + 1 - 1) = (\lambda + 1)*(4 - \lambda^2)\)</span></p>
<p>For <span class="math inline">\(2^{st}\)</span> sub determinant</p>
<p><span class="math inline">\(\begin{vmatrix} 1 &amp; 1 &amp; -1\\ 0 &amp; -2-\lambda &amp; 0\\ 0 &amp; -2 &amp; 2-\lambda \end{vmatrix} = 1 * -(4 - \lambda^2) = -(4-\lambda^2)\)</span></p>
<p>For <span class="math inline">\(3^{st}\)</span> sub determinant</p>
<p><span class="math inline">\(\begin{vmatrix} 1 &amp; -1-\lambda &amp; -1\\ 0 &amp; 2+\lambda &amp; 0\\ 0 &amp; \lambda &amp; 2-\lambda \end{vmatrix} = 1 * (4 - \lambda^2) = (4-\lambda^2)\)</span></p>
<p>For <span class="math inline">\(4^{st}\)</span> sub determinant</p>
<p><span class="math inline">\(\begin{vmatrix} 1 &amp; -1-\lambda &amp; 1 \\ 0 &amp; 2+\lambda &amp; -2-\lambda\\ 0 &amp; \lambda &amp; -2 \end{vmatrix} = 1 * (-4 - 2\lambda + 2\lambda + \lambda^2) = (-4+\lambda^2) = -(4-\lambda^2)\)</span></p>
<p><span class="math inline">\(det(H - \lambda I) = (1 - \lambda)*(\lambda + 1)*(4 - \lambda^2) + (-1) * -(4-\lambda^2) + 1 * (4-\lambda^2) + (-1) * -(4-\lambda^2) = 0\)</span></p>
<p><span class="math inline">\((4-\lambda^2)(1 - \lambda^2 + 1 + 1 + 1) = 0\)</span></p>
<p><span class="math inline">\((4-\lambda^2)(4 - \lambda^2) = 0\)</span></p>
<p><span class="math display">\[ \lambda = \pm 2, \pm 2\]</span></p>
<p>Therefore, The Eigen Values for <span class="math inline">\(H\)</span> are <span class="math inline">\(2, 2, -2, and -2\)</span></p>
</section>
<section id="c" class="level4">
<h4 class="anchored" data-anchor-id="c">(c)</h4>
<p>If A is symmetric then <span class="math inline">\(AA^T = A^TA=A^2\)</span> and <span class="math inline">\(U,V,\sum\)</span> are square matrices. The eigenvectors of <span class="math inline">\(A\)</span> are also eigenvectors of <span class="math inline">\(A^2\)</span> with squared corresponding eigenvalues and the <strong>singular values are the absolute values of the eigenvalues of <span class="math inline">\(A\)</span></strong></p>
<p>Since <span class="math inline">\(H\)</span> is a symmetric matrix, the Singular values of <span class="math inline">\(H\)</span> are <span class="math inline">\(|2|, |2|, |-2|, |-2|\)</span>,</p>
<p>Singular Values of <span class="math inline">\(H = 2,2,2,2\)</span></p>
</section>
</section>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>Calculate the Singular Value Decomposition for the following matrices.</p>
<p><span class="math display">\[
A =
\begin{bmatrix}
1 &amp; -1\\
0 &amp; 1\\
1 &amp; 0\\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
B =
\begin{bmatrix}
1 &amp; 0 &amp; 1\\
-1 &amp; 1 &amp; 0\\
\end{bmatrix}
\]</span></p>
<p>If <span class="math inline">\(A=UΣV^T\)</span> is an <span class="math inline">\(SVD\)</span> for <span class="math inline">\(A\)</span>, Whatcan you say about the <span class="math inline">\(SVD\)</span> for <span class="math inline">\(A^T\)</span> ?</p>
<section id="solution-1" class="level3">
<h3 class="anchored" data-anchor-id="solution-1">Solution</h3>
<p>We know <span class="math inline">\(A=UΣV^T\)</span></p>
<p><span class="math inline">\(A^T = (UΣV^T)^T = (V^T)^TΣ^TU^T = VΣU^T (Σ^T = Σ)\)</span></p>
<p>And, <span class="math inline">\(AA^T = UΣV^TVΣU^T = UΣ^2U^T (V.V^T = I)\)</span></p>
<p><span class="math display">\[
AA^T =
\begin{bmatrix}
2 &amp; -1 &amp; 1\\
-1 &amp; 1 &amp; 0\\
1 &amp; 0 &amp; 1\\
\end{bmatrix}
\]</span></p>
<p>Characteristic Equation to Find Eigen value is <span class="math inline">\(|AA^T - \lambda I| = 0\)</span></p>
<p><span class="math display">\[
|AA^T - \lambda I| =
\begin{vmatrix}
2-\lambda &amp; -1 &amp; 1\\
-1 &amp; 1-\lambda &amp; 0\\
1 &amp; 0 &amp; 1-\lambda\\
\end{vmatrix} = 0
\]</span></p>
<p><span class="math inline">\(1*(0-(1-\lambda)) - 0 + (1-\lambda)*((1-\lambda)*(2-\lambda) - 1) = 0\)</span></p>
<p><span class="math inline">\((1-\lambda)*(-1+\lambda^2-3\lambda+1) = 0\)</span></p>
<p><span class="math inline">\((1-\lambda)*(\lambda^2-3\lambda) = 0\)</span></p>
<p><span class="math inline">\((1-\lambda)* \lambda *(\lambda-3) = 0\)</span></p>
<p><span class="math inline">\(\lambda = 0,1,3\)</span></p>
<p>For <span class="math inline">\(\lambda = 0\)</span></p>
<p><span class="math inline">\(A.v = \lambda.v\)</span></p>
<p><span class="math inline">\((A-\lambda I).v = 0\)</span></p>
<p><span class="math inline">\(\begin{bmatrix} 2 &amp; -1 &amp; 1\\ -1 &amp; 1 &amp; 0\\ 1 &amp; 0 &amp; 1\\ \end{bmatrix} \begin{bmatrix} x_1\\ x_2\\ x_3\\ \end{bmatrix} = 0\)</span></p>
<p>Performing Row Operations</p>
<p><span class="math inline">\(R_1 = R_1/2\)</span><br>
<span class="math inline">\(R_2 = R_2+R_1\)</span><br>
<span class="math inline">\(R_3 = R_3-R_1\)</span><br>
<span class="math inline">\(R_2 = R_2/2\)</span><br>
<span class="math inline">\(R_3 = R_3-0.5*R_2\)</span><br>
<span class="math inline">\(R_1 = R_1-0.5*R_2\)</span></p>
<p><span class="math inline">\(\begin{pmatrix} 1 &amp; 0 &amp; 1\\ 0 &amp; 1 &amp; 1\\ 0 &amp; 0 &amp; 0 \end{pmatrix} \begin{bmatrix} x_1\\ x_2\\ x_3\\ \end{bmatrix} = 0\)</span></p>
<p><span class="math inline">\(x_3 = -x_2\)</span> and <span class="math inline">\(x3 = -x_1\)</span></p>
<p>Eigen Vector corresponding to <span class="math inline">\(\lambda = 0\)</span> is <span class="math inline">\(\begin{bmatrix} -1\\ -1\\ 1\\ \end{bmatrix}\)</span></p>
<p>Similarly the Eigen Vectors for <span class="math inline">\(\lambda = 1\)</span> is <span class="math inline">\(\begin{bmatrix} 0\\ 1\\ 1\\ \end{bmatrix}\)</span></p>
<p>And the Eigen Vectors for <span class="math inline">\(\lambda = 3\)</span> is <span class="math inline">\(\begin{bmatrix} -2\\ 1\\ -1\\ \end{bmatrix}\)</span></p>
<p><span class="math inline">\(Σ^2 = \begin{pmatrix} 3 &amp; 0 &amp; 0\\ 0 &amp; 1 &amp; 0\\ 0 &amp; 0 &amp; 0 \end{pmatrix}\)</span></p>
<p><span class="math inline">\(Σ = \begin{pmatrix} \sqrt3 &amp; 0 &amp; 0\\ 0 &amp; 1 &amp; 0\\ 0 &amp; 0 &amp; 0 \end{pmatrix}\)</span></p>
<p><span class="math inline">\(U = \begin{pmatrix} -2/\sqrt6 &amp; 0 &amp; -1/\sqrt3\\ 1/\sqrt6 &amp; 1/\sqrt2 &amp; -1/\sqrt3\\ -1/\sqrt6 &amp; 1/\sqrt2 &amp; 1/\sqrt3 \end{pmatrix}\)</span></p>
<p>Similarly, <span class="math inline">\(A^TA = VΣU^TUΣV^T = VΣ^2V^T (U.U^T = I)\)</span></p>
<p><span class="math display">\[
AA^T =
\begin{bmatrix}
2 &amp; -1\\
-1 &amp; 2\\
\end{bmatrix}
\]</span></p>
<p>Characteristic Equation to Find Eigen value is <span class="math inline">\(|AA^T - \lambda I| = 0\)</span></p>
<p><span class="math display">\[
|AA^T - \lambda I| =
\begin{bmatrix}
2-\lambda &amp; -1\\
-1 &amp; 2-\lambda\\
\end{bmatrix} = 0
\]</span></p>
<p>$ (2-)^2 - 1 = 0$</p>
<p>$ (2-)^2 = 1$</p>
<p>$ (2-) = $</p>
<p><span class="math inline">\(\lambda = 3,1\)</span></p>
<p>Eigen Vector corresponding to <span class="math inline">\(\lambda = 1\)</span> is <span class="math inline">\(\begin{bmatrix} 1\\ 1\\ \end{bmatrix}\)</span></p>
<p>Similarly the Eigen Vectors for <span class="math inline">\(\lambda = 3\)</span> is <span class="math inline">\(\begin{bmatrix} -1\\ 1\\ \end{bmatrix}\)</span></p>
<p><span class="math inline">\(Σ^2 = \begin{pmatrix} 3 &amp; 0\\ 0 &amp; 1\\ \end{pmatrix}\)</span></p>
<p><span class="math inline">\(Σ = \begin{pmatrix} \sqrt3 &amp; 0\\ 0 &amp; 1\\ \end{pmatrix}\)</span></p>
<p><span class="math inline">\(V = \begin{pmatrix} -1/\sqrt2 &amp; 1/\sqrt2\\ 1/\sqrt2 &amp; 1/\sqrt2\\ \end{pmatrix}\)</span></p>
<p>Hence the <span class="math inline">\(SVD\)</span> of Matrix <span class="math inline">\(A\)</span> is</p>
<p><span class="math display">\[
A = U Σ V^T
\]</span></p>
<p><span class="math display">\[
A =
\begin{pmatrix}
-2/\sqrt6 &amp; 0 &amp; -1/\sqrt3\\
1/\sqrt6 &amp; 1/\sqrt2 &amp; -1/\sqrt3\\
-1/\sqrt6 &amp; 1/\sqrt2 &amp; 1/\sqrt3
\end{pmatrix}
\begin{pmatrix}
\sqrt3 &amp; 0\\
0 &amp; 1\\
0 &amp; 0
\end{pmatrix}
\begin{pmatrix}
-1/\sqrt2 &amp; 1/\sqrt2\\
1/\sqrt2 &amp; 1/\sqrt2\\
\end{pmatrix}
\]</span></p>
<section id="verification" class="level4">
<h4 class="anchored" data-anchor-id="verification">Verification</h4>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.array([</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>,<span class="dv">1</span>],</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>,<span class="dv">0</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>U <span class="op">=</span> np.array([</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">2</span><span class="op">/</span>np.sqrt(<span class="dv">6</span>), <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">3</span>)],</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">6</span>), <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>), <span class="op">-</span><span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">3</span>)],</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">6</span>), <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>), <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">3</span>)]</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>S <span class="op">=</span> np.array([</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    [np.sqrt(<span class="dv">3</span>), <span class="dv">0</span>],</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>,<span class="dv">1</span>],</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>,<span class="dv">0</span>]</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>Vt <span class="op">=</span> np.array([</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>), <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>)],</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>), <span class="dv">1</span><span class="op">/</span>np.sqrt(<span class="dv">2</span>)]</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>np.allclose(A, np.matmul(U,np.matmul(S,Vt)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">
<pre><code>True</code></pre>
</div>
</div>
<p>Given <span class="math display">\[
B =
\begin{bmatrix}
1 &amp; 0 &amp; 1\\
-1 &amp; 1 &amp; 0\\
\end{bmatrix} = A^T
\]</span></p>
<p><span class="math inline">\(SVD(B) = SVD(A^T)\)</span></p>
<p>We Know, <span class="math inline">\(SVD(A) = U Σ V^T\)</span></p>
<p><span class="math inline">\(SVD(A^T) = (U Σ V^T)^T\)</span></p>
<p><span class="math inline">\(SVD(A^T) = (V Σ^T U^T)\)</span></p>
<p>Hence the <span class="math inline">\(SVD\)</span> of Matrix <span class="math inline">\(B\)</span> is</p>
<p><span class="math display">\[
B = V Σ^T U^T
\]</span></p>
<p>Where <span class="math inline">\(U,Σ,V\)</span> are from Matrix <span class="math inline">\(A\)</span></p>
<p><span class="math display">\[
A =
\begin{pmatrix}
-1/\sqrt2 &amp; 1/\sqrt2\\
1/\sqrt2 &amp; 1/\sqrt2\\
\end{pmatrix}
\begin{pmatrix}
\sqrt3 &amp; 0\\
0 &amp; 1\\
0 &amp; 0
\end{pmatrix}
\begin{pmatrix}
-2/\sqrt6 &amp; 1/\sqrt6 &amp; -1/\sqrt6\\
0 &amp; 1/\sqrt2 &amp; 1/\sqrt2\\
-1/\sqrt3 &amp; -1/\sqrt3 &amp; 1/\sqrt3
\end{pmatrix}
\]</span></p>
</section>
<section id="verification-1" class="level4">
<h4 class="anchored" data-anchor-id="verification-1">Verification</h4>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> np.array([</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>],</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>np.allclose(B, np.matmul(Vt.T,np.matmul(S.T,U.T)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<pre><code>True</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>In image processing, consider this situation: A satellite takes a picture and wants to send it to Earth. In order to do that, a compression is used. Take an image from the web of Einstein. Apply SVD on the 2D image and compress it to <code>30%</code> singular values (make the 70% lower singular values as zero). Depict the original image and the compressed image and comment.</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>einstein <span class="op">=</span> Image.<span class="bu">open</span>(<span class="st">"./data/Albert_Einstein_Head.jpg"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(einstein.size)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>einstein_arary <span class="op">=</span> np.array(einstein)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(einstein_arary.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(3250, 4333)
(4333, 3250)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>u, s, vt <span class="op">=</span> np.linalg.svd(einstein_arary, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>u.shape, s.shape, vt.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>((4333, 3250), (3250,), (3250, 3250))</code></pre>
</div>
</div>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>RETENTION_FACTOR <span class="op">=</span> [<span class="fl">0.5</span>,<span class="fl">0.3</span>,<span class="fl">0.1</span>,<span class="fl">0.01</span>]</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>reduced_einstein <span class="op">=</span> []</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> RETENTION_FACTOR:</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    new_s <span class="op">=</span> s.copy()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    new_s[<span class="bu">int</span>(<span class="bu">len</span>(s)<span class="op">*</span>r):] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    reduced_einstein.append(np.dot(u<span class="op">*</span>new_s, vt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="106">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>f,ax <span class="op">=</span> plt.subplots(ncols<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>f.set_size_inches(<span class="dv">15</span>,<span class="dv">40</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Original image'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].imshow(einstein_arary, cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>titles <span class="op">=</span> [<span class="st">'50% Retained (50% Compression)'</span>, <span class="st">'30% Retained (70% Compression)'</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">'10% Retained (90% Compression)'</span>, <span class="st">'1% Retained (99% Compression)'</span>]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    ax[i<span class="op">+</span><span class="dv">1</span>].set_title(titles[i])</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    ax[i<span class="op">+</span><span class="dv">1</span>].imshow(reduced_einstein[i], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a <span class="kw">in</span> ax:</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    a.xaxis.set_visible(<span class="va">False</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    a.yaxis.set_visible(<span class="va">False</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Syed_AbdulKhader_HW1_files/figure-html/cell-8-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>After performing SVD on the image of size 4333 x 3250, we got 3250 Singular Value in the Diagonal Matrix <span class="math inline">\(Σ\)</span>, of which we are using the highest 30%, which is 975 singular values and making all the other as zero, to compress the image by 70%.</p>
<p>Even after compressing the image to 70% and retaning only 30% of the data, the Einstein is clear in the image and only the very fine details in the image are lost.</p>
<p>This was even more evident when we loss 99% of the singular values and only use top 1%, which makes the image blurry due to high loss of data. But even than the person in the image is clearly visible.</p>
</section>
<section id="problem-4" class="level2">
<h2 class="anchored" data-anchor-id="problem-4">Problem 4</h2>
<p>Calculate the Gradient of the following functions</p>
<ol type="a">
<li><p><span class="math inline">\(f(x,y)=x+3y^2\)</span>,</p></li>
<li><p><span class="math inline">\(f(x,y)=\sqrt{x^2+y^2}\)</span></p></li>
</ol>
<section id="solution-2" class="level3">
<h3 class="anchored" data-anchor-id="solution-2">Solution</h3>
<section id="a-1" class="level4">
<h4 class="anchored" data-anchor-id="a-1">(a)</h4>
<p><span class="math display">\[
\triangledown f(x,y) =
\begin{bmatrix}
\frac{\partial f}{\partial x}\\
\frac{\partial f}{\partial y}
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = \frac{\partial (x+3y^2)}{\partial x}
= 1
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = \frac{\partial (x+3y^2)}{\partial y}
= 6y
\]</span></p>
<p><span class="math inline">\(\triangledown f(x,y) = \begin{bmatrix} 1\\ 6y \end{bmatrix}\)</span></p>
</section>
</section>
<section id="b-1" class="level3">
<h3 class="anchored" data-anchor-id="b-1">(b)</h3>
<p><span class="math display">\[
\triangledown f(x,y) =
\begin{bmatrix}
\frac{\partial f}{\partial x}\\
\frac{\partial f}{\partial y}
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = \frac{\partial (\sqrt{x^2+y^2})}{\partial x}
= \frac{x}{\sqrt{x^2+y^2}}
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = \frac{\partial (\sqrt{x^2+y^2})}{\partial y}
= \frac{y}{\sqrt{x^2+y^2}}
\]</span></p>
<p><span class="math inline">\(\triangledown f(x,y) = \begin{bmatrix} \frac{x}{\sqrt{x^2+y^2}}\\ \frac{y}{\sqrt{x^2+y^2}} \end{bmatrix}\)</span></p>
</section>
</section>
<section id="problem-5" class="level2">
<h2 class="anchored" data-anchor-id="problem-5">Problem 5</h2>
<p>Consider the optimization problem:</p>
<p>minimize <span class="math inline">\((1/2)x^TPx + q^Tx + r\)</span></p>
<p>subject to <span class="math inline">\(−1≤x_i≤1, i=1,2,3\)</span></p>
<p>where,</p>
<p><span class="math display">\[
P = \begin{bmatrix}
13 &amp; 12 &amp; -2\\
12 &amp; 17 &amp; 6\\
-2 &amp; 6 &amp; 12\\
\end{bmatrix},
q = \begin{bmatrix}
-22\\
-14.5\\
13.0\\
\end{bmatrix},
r = 1
\]</span></p>
<ol type="a">
<li><p>Show that the problem is convex ( Hint : <span class="math inline">\(x^TAx\)</span> is convex if <span class="math inline">\(A\)</span> is positive semi-definite)</p></li>
<li><p>Solve the optimization problem using Projected Gradient Descent method.</p></li>
<li><p>Attempt to solve the problem mathematically and find the optimal solution</p></li>
</ol>
<section id="solution-3" class="level3">
<h3 class="anchored" data-anchor-id="solution-3">Solution</h3>
<section id="a-2" class="level4">
<h4 class="anchored" data-anchor-id="a-2">(a)</h4>
<p>To prove the minimization equation is convex, we can prove that each component is convex. The term <span class="math inline">\(q^Tx\)</span> is linear and hence convex, so we only need to prove <span class="math inline">\(x^TPx\)</span> is convex to proof the entire equation is convex</p>
<p>We know (from Hint), <span class="math inline">\(x^TAx\)</span> is convex if <span class="math inline">\(A\)</span> is positive semi-definite, which means A should have non-negative eigen values.</p>
<p>For Eigen Values of P, we need to solve the Characteristic equation which is <span class="math inline">\(|P - \lambda I| = 0\)</span></p>
<p><span class="math display">\[
|P-\lambda I| =
\begin{vmatrix}
13-\lambda &amp; 12 &amp; -2\\
12 &amp; 17-\lambda &amp; 6\\
-2 &amp; 6 &amp; 12-\lambda
\end{vmatrix} = 0
\]</span></p>
<p>(Using Triangle’s Rule) <span class="math display">\[
(-λ+13)*(-λ+17)*(-λ+12)+12*6*(-2)+\\
(-2)*12*6-(-2)*(-λ+17)*(-2)-6*\\6*(-λ+13)-(-λ+12)*12*12 = 0
\]</span></p>
<p><span class="math display">\[-λ^3+42*λ^2-397*λ+100 = 0\]</span></p>
<p>Solving it using a solver, we get</p>
<p><span class="math display">\[\lambda = 0.259, 13.843, 27.898\]</span></p>
<p>Since, all the Eigen Values of P are positive, P is positive semi-definite matrix, hence <span class="math inline">\(x^TPx\)</span> is convex.</p>
<p>The entire equation <span class="math inline">\((1/2)x^TPx + q^Tx + r\)</span> is <strong>convex</strong></p>
</section>
<section id="b-2" class="level4">
<h4 class="anchored" data-anchor-id="b-2">(b)</h4>
<div class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="fl">1.9</span>,<span class="op">-</span><span class="fl">1.5</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>np.sign(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="79">
<pre><code>array([ 1., -1.])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="111">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> func(x, P, q, r):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (x.T<span class="op">@</span>P)<span class="op">@</span>x <span class="op">+</span> q.T<span class="op">@</span>x <span class="op">+</span> r</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> func_diff(x, P, q, r):</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> P.T<span class="op">@</span>x <span class="op">+</span> q</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> update_x(x, grad, alpha<span class="op">=</span><span class="fl">0.0001</span>):</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    x  <span class="op">=</span> x <span class="op">-</span> alpha<span class="op">*</span>grad</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take Minimum Value of Element or 1</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Multiply by it's original sign to get back sign</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.minimum(<span class="dv">1</span>,np.<span class="bu">abs</span>(x)) <span class="op">*</span> np.sign(x)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="112">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.random(<span class="dv">3</span>).reshape(<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>P <span class="op">=</span> np.array([</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">13</span>,<span class="dv">12</span>,<span class="op">-</span><span class="dv">2</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">6</span>],</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">12</span>]</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">22</span>,<span class="op">-</span><span class="fl">14.5</span>, <span class="dv">13</span>]).reshape(<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">100_000</span>):</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> update_x(x, func_diff(x,P,q,r)) </span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="112">
<pre><code>array([[ 1. ],
       [ 0.5],
       [-1. ]])</code></pre>
</div>
</div>
</section>
<section id="c-1" class="level4">
<h4 class="anchored" data-anchor-id="c-1">(c)</h4>
<p>Constrained Optimization</p>
<p><span class="math display">\[
f(x) = (1/2)x^TPx + q^Tx + r + \lambda_1 (x - 1) + \lambda_2 (x + 1)
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial \lambda_1} = x-1 = 0\\
x = 1\\
x =
\begin{bmatrix}
1\\
1\\
1\\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial \lambda_2} = x+1 = 0\\
x = -1\\x =
\begin{bmatrix}
-1\\
-1\\
-1\\
\end{bmatrix}
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = 1/2(P + P^T)x + q^T + \lambda_1 + \lambda_2
\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = Px + q^T + \lambda_1 + \lambda_2
\]</span></p>
<p><span class="math display">\[\frac{\partial f}{\partial x} = 0\]</span></p>
<p><span class="math display">\[\lambda_1 = 0, \lambda_2 = 0\]</span></p>
<p><span class="math display">\[
\frac{\partial f}{\partial x} = 0\\
Px + q^T = 0
\]</span></p>
<p>Putting Values of P and q <span class="math display">\[
\begin{bmatrix}
13 &amp; 12 &amp; -2\\
12 &amp; 17 &amp; 6\\
-2 &amp; 6 &amp; 12\\
\end{bmatrix}.
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
\end{bmatrix} +
\begin{bmatrix}
-22\\
-14.5\\
13.0\\
\end{bmatrix} = 0
\]</span></p>
<p><span class="math display">\[
13x_1 + 12x_2 - 2x_3 - 22 = 0
\]</span> <span class="math display">\[
12x_1 + 17x_2 + 6x_3 - 14.5 = 0
\]</span> <span class="math display">\[
-2x_1 + 6x_2 + 12x_3 + 13 = 0
\]</span></p>
<p>On solving for <span class="math inline">\(x_1, x_2 and x_3\)</span>, we get</p>
<p><span class="math display">\[x =
\begin{bmatrix}
0.56\\
0.98\\
-1.48\\
\end{bmatrix}
\]</span></p>
<p>Finally <span class="math display">\[
x =
\begin{bmatrix}
1\\
1\\
1\\
\end{bmatrix},
\begin{bmatrix}
-1\\
-1\\
-1\\
\end{bmatrix},
\begin{bmatrix}
0.56\\
0.98\\
-1.48\\
\end{bmatrix}
\]</span></p>
<p>Selecting the minimum values to be under constrain:</p>
<p><span class="math display">\[
x =
\begin{bmatrix}
0.56\\
0.98\\
-1\\
\end{bmatrix}
\]</span></p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.random(<span class="dv">3</span>).reshape(<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>P <span class="op">=</span> np.array([</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">13</span>,<span class="dv">12</span>,<span class="op">-</span><span class="dv">2</span>],</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">12</span>,<span class="dv">17</span>,<span class="dv">6</span>],</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">2</span>,<span class="dv">6</span>,<span class="dv">12</span>]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>q <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">22</span>,<span class="op">-</span><span class="fl">14.5</span>, <span class="dv">13</span>])</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array([<span class="fl">0.56</span>, <span class="fl">0.98</span>, <span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>P<span class="op">@</span>x.T <span class="op">+</span> q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([-0.96,  2.88,  5.76])</code></pre>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>